project:
  type: website
  output-dir: _site

execute:
    freeze: auto

website:
  title: "Raghavendra N. V."
  google-analytics: "G-3WBQC1YBVT"
  cookie-consent: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: experience.qmd
        text: Experience
      - href: 404.qmd
        text: Blog
      - href: contact.qmd
        text: Contact
  page-footer:
    center: |
      © 2024 Venkata Raghavendra. All rights reserved. | Designed with [Quarto](https://quarto.org/)

format:
  html:
    theme: journal
      # light: journal
      # dark: journal
    css: styles.css
    toc: false
    code-fold: false
    highlight-style: github
